### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by MPLedward** [tuxtof/cs-mikrotik-bouncer#3]
Great project.  Are you planning on making the password handling more secure?  I'd be worried that someone in my network could gain access to my firewall.

**Comment by tuxtof** [comment]
Hello @MPLedward 

This bouncer don't handle directly password , they just consume it from an external source through a ENV variable.

Depending on how you run it (docker, k8s, ..) you have different choice for managing it in a secure way

with Docker you can rely on docker secrets
with k8s , you can use secret ressource or external vault and native k8s integration (ex: https://github.com/external-secrets/external-secrets)

**Comment by MPLedward** [comment]
Thanks for your reply!  I'm new to both docker and Go, so my question probably shows my ignorance.  I'll look more into this, thanks for the link.  If you happen to think of any more links that may be helpful to bringing a n00b up to speed more quickly, I'd appreciate it.  :)

**Comment by tuxtof** [comment]
No problem @MPLedward 

to strength your knowledge I can advice you https://medium.com ,a lot of great articles, whatever the subject your want to dig.

take care
