### ISSUE TITLE
Add support for IPv6 address list 

### ISSUE THREAD

**Issue by zleppy** [tuxtof/cs-mikrotik-bouncer#4]
Would be great to see ipv6 support. 
Since a lot of the Scenarios also have IPv6 support. 

suggest just calling it crowdsec_ipv6 

add action=drop src-address-list=crowdsec_ipv6 chain=forward/input

**Comment by tuxtof** [comment]
Hello @zleppy 

Ipv6 support added in #5 

I let you test and give me feedback

**Comment by zleppy** [comment]
Nice! Works perfectly!

**Comment by tuxtof** [comment]
Good to hear
